### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [akash14204/Student-Budget-Tracker#2]
With your great project being open source, would you mind publishing the `.apk` here at Github (best with `releases/`, see [Creating Releases](https://help.github.com/articles/creating-releases/) in the Github help)? That way people w/o Playstore could benefit from it. I'd then immediately pick it into [my F-Droid compatible repo](https://android.izzysoft.de/repo) to make it easy to install and easy to keep up-to-date.

Of course, bringing it into the official F-Droid repo would be a greater goal, if you don't mind the effort :smile_cat: 

Thanks in advance!

**Comment by akash14204** [comment]
Thanks

**Comment by IzzySoft** [comment]
Done or gone? I don't see the `.apk`.

**Comment by akash14204** [comment]
https://play.google.com/store/apps/details?id=com.magic.akash.magicbox   goto playstore

**Comment by IzzySoft** [comment]
No way. There are no GApps on the device, and Playstore doesn't allow for downloading the APK directly. Please read my initial post again ;)
